name: Mirror the repo to bitbucket
on: [push]

jobs:
  bitbucket-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in bitbucket
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.6.0
        with:
          REMOTE: 'https://anas-elgarhy@bitbucket.org/archy-linux/archy-slstatus.git'
          REMOTE_NAME: bitbucket
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.BITBUCKET_TOKEN }}
