name: Mirror the repo to disroot
on: [push]

jobs:
  disroot-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in git.disroot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.6.0
        with:
          REMOTE: 'https://git.disroot.org/archy-linux/archy-slstatus.git'
          REMOTE_NAME: disroot
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.DISROOT_TOKEN }}
