name: Mirror the repo to Gitdab
on: [ push ]

jobs:
  gitdab-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in Gitdab
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.6.0
        with:
          REMOTE: 'https://gitdab.com/archy-linux/archy-slstatus.git'
          REMOTE_NAME: gitdab
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.GITDAB_TOKEN }}
