name: Mirror the repo to Gitea
on: [ push ]

jobs:
  gitea-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in Gitea
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.6.0
        with:
          REMOTE: 'https://gitea.com/archy-linux/archy-slstatus.git'
          REMOTE_NAME: gitea
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.GITEA_TOKEN }}
